var searchData=
[
  ['scheduleinoutevent_1236',['ScheduleInOutEvent',['https://libctru.devkitpro.org/structScheduleInOutEvent.html',1,'']]],
  ['shaderinstance_5fs_1237',['shaderInstance_s',['https://libctru.devkitpro.org/structshaderInstance__s.html',1,'']]],
  ['shaderprogram_5fs_1238',['shaderProgram_s',['https://libctru.devkitpro.org/structshaderProgram__s.html',1,'']]],
  ['sockaddr_1239',['sockaddr',['https://libctru.devkitpro.org/structsockaddr.html',1,'']]],
  ['sockaddr_5fin_1240',['sockaddr_in',['https://libctru.devkitpro.org/structsockaddr__in.html',1,'']]],
  ['sockaddr_5fstorage_1241',['sockaddr_storage',['https://libctru.devkitpro.org/structsockaddr__storage.html',1,'']]],
  ['socu_5farptableentry_1242',['SOCU_ARPTableEntry',['https://libctru.devkitpro.org/structSOCU__ARPTableEntry.html',1,'']]],
  ['socu_5fdnstableentry_1243',['SOCU_DNSTableEntry',['https://libctru.devkitpro.org/structSOCU__DNSTableEntry.html',1,'']]],
  ['socu_5fipinfo_1244',['SOCU_IPInfo',['https://libctru.devkitpro.org/structSOCU__IPInfo.html',1,'']]],
  ['socu_5froutingtableentry_1245',['SOCU_RoutingTableEntry',['https://libctru.devkitpro.org/structSOCU__RoutingTableEntry.html',1,'']]],
  ['socu_5ftcptableentry_1246',['SOCU_TCPTableEntry',['https://libctru.devkitpro.org/structSOCU__TCPTableEntry.html',1,'']]],
  ['socu_5fudptableentry_1247',['SOCU_UDPTableEntry',['https://libctru.devkitpro.org/structSOCU__UDPTableEntry.html',1,'']]],
  ['sslccontext_1248',['sslcContext',['https://libctru.devkitpro.org/structsslcContext.html',1,'']]],
  ['startupinfo_1249',['StartupInfo',['https://libctru.devkitpro.org/structStartupInfo.html',1,'']]],
  ['stoppointexceptionevent_1250',['StopPointExceptionEvent',['https://libctru.devkitpro.org/structStopPointExceptionEvent.html',1,'']]],
  ['swkbddictword_1251',['SwkbdDictWord',['https://libctru.devkitpro.org/structSwkbdDictWord.html',1,'']]],
  ['swkbdextra_1252',['SwkbdExtra',['https://libctru.devkitpro.org/structSwkbdExtra.html',1,'']]],
  ['swkbdlearningdata_1253',['SwkbdLearningData',['https://libctru.devkitpro.org/structSwkbdLearningData.html',1,'']]],
  ['swkbdstate_1254',['SwkbdState',['https://libctru.devkitpro.org/structSwkbdState.html',1,'']]],
  ['swkbdstatusdata_1255',['SwkbdStatusData',['https://libctru.devkitpro.org/structSwkbdStatusData.html',1,'']]],
  ['syscallinoutevent_1256',['SyscallInOutEvent',['https://libctru.devkitpro.org/structSyscallInOutEvent.html',1,'']]]
];
