var searchData=
[
  ['errf_5fexceptiondata_1134',['ERRF_ExceptionData',['https://libctru.devkitpro.org/structERRF__ExceptionData.html',1,'']]],
  ['errf_5fexceptioninfo_1135',['ERRF_ExceptionInfo',['https://libctru.devkitpro.org/structERRF__ExceptionInfo.html',1,'']]],
  ['errf_5ffatalerrinfo_1136',['ERRF_FatalErrInfo',['https://libctru.devkitpro.org/structERRF__FatalErrInfo.html',1,'']]],
  ['errorconf_1137',['errorConf',['https://libctru.devkitpro.org/structerrorConf.html',1,'']]],
  ['exceptionevent_1138',['ExceptionEvent',['https://libctru.devkitpro.org/structExceptionEvent.html',1,'']]],
  ['exheader_1139',['ExHeader',['https://libctru.devkitpro.org/structExHeader.html',1,'']]],
  ['exheader_5faccesscontrolinfo_1140',['ExHeader_AccessControlInfo',['https://libctru.devkitpro.org/structExHeader__AccessControlInfo.html',1,'']]],
  ['exheader_5faccessdescriptor_1141',['ExHeader_AccessDescriptor',['https://libctru.devkitpro.org/structExHeader__AccessDescriptor.html',1,'']]],
  ['exheader_5farm11coreinfo_1142',['ExHeader_Arm11CoreInfo',['https://libctru.devkitpro.org/structExHeader__Arm11CoreInfo.html',1,'']]],
  ['exheader_5farm11kernelcapabilities_1143',['ExHeader_Arm11KernelCapabilities',['https://libctru.devkitpro.org/structExHeader__Arm11KernelCapabilities.html',1,'']]],
  ['exheader_5farm11storageinfo_1144',['ExHeader_Arm11StorageInfo',['https://libctru.devkitpro.org/structExHeader__Arm11StorageInfo.html',1,'']]],
  ['exheader_5farm11systemlocalcapabilities_1145',['ExHeader_Arm11SystemLocalCapabilities',['https://libctru.devkitpro.org/structExHeader__Arm11SystemLocalCapabilities.html',1,'']]],
  ['exheader_5farm9accesscontrol_1146',['ExHeader_Arm9AccessControl',['https://libctru.devkitpro.org/structExHeader__Arm9AccessControl.html',1,'']]],
  ['exheader_5fcodesectioninfo_1147',['ExHeader_CodeSectionInfo',['https://libctru.devkitpro.org/structExHeader__CodeSectionInfo.html',1,'']]],
  ['exheader_5fcodesetinfo_1148',['ExHeader_CodeSetInfo',['https://libctru.devkitpro.org/structExHeader__CodeSetInfo.html',1,'']]],
  ['exheader_5finfo_1149',['ExHeader_Info',['https://libctru.devkitpro.org/structExHeader__Info.html',1,'']]],
  ['exheader_5fsystemcontrolinfo_1150',['ExHeader_SystemControlInfo',['https://libctru.devkitpro.org/structExHeader__SystemControlInfo.html',1,'']]],
  ['exheader_5fsysteminfo_1151',['ExHeader_SystemInfo',['https://libctru.devkitpro.org/structExHeader__SystemInfo.html',1,'']]],
  ['exheader_5fsysteminfoflags_1152',['ExHeader_SystemInfoFlags',['https://libctru.devkitpro.org/structExHeader__SystemInfoFlags.html',1,'']]],
  ['exitprocessevent_1153',['ExitProcessEvent',['https://libctru.devkitpro.org/structExitProcessEvent.html',1,'']]],
  ['exitthreadevent_1154',['ExitThreadEvent',['https://libctru.devkitpro.org/structExitThreadEvent.html',1,'']]]
];
