var searchData=
[
  ['scheduleinoutevent_0',['ScheduleInOutEvent',['https://libctru.devkitpro.org/structScheduleInOutEvent.html',1,'']]],
  ['shaderinstance_5fs_1',['shaderInstance_s',['https://libctru.devkitpro.org/structshaderInstance__s.html',1,'']]],
  ['shaderprogram_5fs_2',['shaderProgram_s',['https://libctru.devkitpro.org/structshaderProgram__s.html',1,'']]],
  ['sockaddr_3',['sockaddr',['https://libctru.devkitpro.org/structsockaddr.html',1,'']]],
  ['sockaddr_5fin_4',['sockaddr_in',['https://libctru.devkitpro.org/structsockaddr__in.html',1,'']]],
  ['sockaddr_5fstorage_5',['sockaddr_storage',['https://libctru.devkitpro.org/structsockaddr__storage.html',1,'']]],
  ['socu_5farptableentry_6',['SOCU_ARPTableEntry',['https://libctru.devkitpro.org/structSOCU__ARPTableEntry.html',1,'']]],
  ['socu_5fdnstableentry_7',['SOCU_DNSTableEntry',['https://libctru.devkitpro.org/structSOCU__DNSTableEntry.html',1,'']]],
  ['socu_5fipinfo_8',['SOCU_IPInfo',['https://libctru.devkitpro.org/structSOCU__IPInfo.html',1,'']]],
  ['socu_5froutingtableentry_9',['SOCU_RoutingTableEntry',['https://libctru.devkitpro.org/structSOCU__RoutingTableEntry.html',1,'']]],
  ['socu_5ftcptableentry_10',['SOCU_TCPTableEntry',['https://libctru.devkitpro.org/structSOCU__TCPTableEntry.html',1,'']]],
  ['socu_5fudptableentry_11',['SOCU_UDPTableEntry',['https://libctru.devkitpro.org/structSOCU__UDPTableEntry.html',1,'']]],
  ['sslccontext_12',['sslcContext',['https://libctru.devkitpro.org/structsslcContext.html',1,'']]],
  ['startupinfo_13',['StartupInfo',['https://libctru.devkitpro.org/structStartupInfo.html',1,'']]],
  ['stoppointexceptionevent_14',['StopPointExceptionEvent',['https://libctru.devkitpro.org/structStopPointExceptionEvent.html',1,'']]],
  ['swkbddictword_15',['SwkbdDictWord',['https://libctru.devkitpro.org/structSwkbdDictWord.html',1,'']]],
  ['swkbdextra_16',['SwkbdExtra',['https://libctru.devkitpro.org/structSwkbdExtra.html',1,'']]],
  ['swkbdlearningdata_17',['SwkbdLearningData',['https://libctru.devkitpro.org/structSwkbdLearningData.html',1,'']]],
  ['swkbdstate_18',['SwkbdState',['https://libctru.devkitpro.org/structSwkbdState.html',1,'']]],
  ['swkbdstatusdata_19',['SwkbdStatusData',['https://libctru.devkitpro.org/structSwkbdStatusData.html',1,'']]],
  ['syscallinoutevent_20',['SyscallInOutEvent',['https://libctru.devkitpro.org/structSyscallInOutEvent.html',1,'']]]
];
