var searchData=
[
  ['faultexceptionevent_0',['FaultExceptionEvent',['https://libctru.devkitpro.org/structFaultExceptionEvent.html',1,'']]],
  ['finf_5fs_1',['FINF_s',['https://libctru.devkitpro.org/structFINF__s.html',1,'']]],
  ['float24uniform_5fs_2',['float24Uniform_s',['https://libctru.devkitpro.org/structfloat24Uniform__s.html',1,'']]],
  ['fontglyphpos_5fs_3',['fontGlyphPos_s',['https://libctru.devkitpro.org/structfontGlyphPos__s.html',1,'']]],
  ['fpuregisters_4',['FpuRegisters',['https://libctru.devkitpro.org/structFpuRegisters.html',1,'']]],
  ['friendkey_5',['FriendKey',['https://libctru.devkitpro.org/structFriendKey.html',1,'']]],
  ['friendprofile_6',['FriendProfile',['https://libctru.devkitpro.org/structFriendProfile.html',1,'']]],
  ['fs_5farchiveresource_7',['FS_ArchiveResource',['https://libctru.devkitpro.org/structFS__ArchiveResource.html',1,'']]],
  ['fs_5fdevicemovecontext_8',['FS_DeviceMoveContext',['https://libctru.devkitpro.org/structFS__DeviceMoveContext.html',1,'']]],
  ['fs_5fdirectoryentry_9',['FS_DirectoryEntry',['https://libctru.devkitpro.org/structFS__DirectoryEntry.html',1,'']]],
  ['fs_5fextsavedatainfo_10',['FS_ExtSaveDataInfo',['https://libctru.devkitpro.org/structFS__ExtSaveDataInfo.html',1,'']]],
  ['fs_5fintegrityverificationseed_11',['FS_IntegrityVerificationSeed',['https://libctru.devkitpro.org/structFS__IntegrityVerificationSeed.html',1,'']]],
  ['fs_5fpath_12',['FS_Path',['https://libctru.devkitpro.org/structFS__Path.html',1,'']]],
  ['fs_5fproductinfo_13',['FS_ProductInfo',['https://libctru.devkitpro.org/structFS__ProductInfo.html',1,'']]],
  ['fs_5fprograminfo_14',['FS_ProgramInfo',['https://libctru.devkitpro.org/structFS__ProgramInfo.html',1,'']]],
  ['fs_5fsdmmcspeedinfo_15',['FS_SdMmcSpeedInfo',['https://libctru.devkitpro.org/structFS__SdMmcSpeedInfo.html',1,'']]],
  ['fs_5fsystemsavedatainfo_16',['FS_SystemSaveDataInfo',['https://libctru.devkitpro.org/structFS__SystemSaveDataInfo.html',1,'']]]
];
