var searchData=
[
  ['scheduleinoutevent_1224',['ScheduleInOutEvent',['https://libctru.devkitpro.org/structScheduleInOutEvent.html',1,'']]],
  ['shaderinstance_5fs_1225',['shaderInstance_s',['https://libctru.devkitpro.org/structshaderInstance__s.html',1,'']]],
  ['shaderprogram_5fs_1226',['shaderProgram_s',['https://libctru.devkitpro.org/structshaderProgram__s.html',1,'']]],
  ['sockaddr_1227',['sockaddr',['https://libctru.devkitpro.org/structsockaddr.html',1,'']]],
  ['sockaddr_5fin_1228',['sockaddr_in',['https://libctru.devkitpro.org/structsockaddr__in.html',1,'']]],
  ['sockaddr_5fstorage_1229',['sockaddr_storage',['https://libctru.devkitpro.org/structsockaddr__storage.html',1,'']]],
  ['socu_5farptableentry_1230',['SOCU_ARPTableEntry',['https://libctru.devkitpro.org/structSOCU__ARPTableEntry.html',1,'']]],
  ['socu_5fdnstableentry_1231',['SOCU_DNSTableEntry',['https://libctru.devkitpro.org/structSOCU__DNSTableEntry.html',1,'']]],
  ['socu_5fipinfo_1232',['SOCU_IPInfo',['https://libctru.devkitpro.org/structSOCU__IPInfo.html',1,'']]],
  ['socu_5froutingtableentry_1233',['SOCU_RoutingTableEntry',['https://libctru.devkitpro.org/structSOCU__RoutingTableEntry.html',1,'']]],
  ['socu_5ftcptableentry_1234',['SOCU_TCPTableEntry',['https://libctru.devkitpro.org/structSOCU__TCPTableEntry.html',1,'']]],
  ['socu_5fudptableentry_1235',['SOCU_UDPTableEntry',['https://libctru.devkitpro.org/structSOCU__UDPTableEntry.html',1,'']]],
  ['sslccontext_1236',['sslcContext',['https://libctru.devkitpro.org/structsslcContext.html',1,'']]],
  ['startupinfo_1237',['StartupInfo',['https://libctru.devkitpro.org/structStartupInfo.html',1,'']]],
  ['stoppointexceptionevent_1238',['StopPointExceptionEvent',['https://libctru.devkitpro.org/structStopPointExceptionEvent.html',1,'']]],
  ['swkbddictword_1239',['SwkbdDictWord',['https://libctru.devkitpro.org/structSwkbdDictWord.html',1,'']]],
  ['swkbdextra_1240',['SwkbdExtra',['https://libctru.devkitpro.org/structSwkbdExtra.html',1,'']]],
  ['swkbdlearningdata_1241',['SwkbdLearningData',['https://libctru.devkitpro.org/structSwkbdLearningData.html',1,'']]],
  ['swkbdstate_1242',['SwkbdState',['https://libctru.devkitpro.org/structSwkbdState.html',1,'']]],
  ['swkbdstatusdata_1243',['SwkbdStatusData',['https://libctru.devkitpro.org/structSwkbdStatusData.html',1,'']]],
  ['syscallinoutevent_1244',['SyscallInOutEvent',['https://libctru.devkitpro.org/structSyscallInOutEvent.html',1,'']]]
];
